sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t lchase/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lchase/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-121859637847"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY